version: '3.6'

services:
    postgres:
        container_name: postgres_container
        image: postgres:10.13-alpine
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "@1234Fd#"
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
  
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
            PGADMIN_DEFAULT_PASSWORD: "@1234Fd#"
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped

    backend:
        container_name: backend_container
        build :
            context: .
            dockerfile: Dockerfile        
        ports:
            - "4001:4001"
        environment :
            - ASPNETCORE_ENVIRONMENT=Production
        networks:
            - postgres
        restart: unless-stopped
        depends_on :
            - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: 