version: "3.6"

services:
    appfullstackdemo.database:
        container_name: mssqlserver
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
        environment:
            SA_PASSWORD: "@1234Fd#"
            ACCEPT_EULA: "Y"
        ports:
            - "4002:1433"    
    
    appfullstackdemo.backend:
        container_name: webapi
        build :
            context: .
            dockerfile: Dockerfile
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
        ports :
            - 4001:4001
        environment :            
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on :
            - appfullstackdemo.database
        ports:
            - "4001:4001"

    appfullstackdemo.sqltools:
        container_name: mssqlservertools
        image: mcr.microsoft.com/mssql-tools
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16