version: ''

networks: 
  appfullstackdemo-network:
    driver: bridge

services:
  dockersql.application.webapi:
    container_name: appfullstackdemo_webapi
    image: dockersql.application.webapi
    build:
      context: .
      dockerfile: BackEnd/AppFullStackDemo.Api/Dockerfile
    networks:
      - appfullstackdemo-network
    depends_on:
      - sql.database

  sql.database:
    container_name: appfullstackdemo_webapi.database
    image: microsoft/mssql-server-linux:2017-latest
    networks:
      - appfullstackdemo-network




































version: "3"
volumes:
    studentsdata:
networks:
    backend:

services:
    mysql:
        image: "mysql:5.7"
        volumes:
            - studentsdata:/var/lib/mysql
            - ./MySqlInitScript:/docker-entrypoint-initdb.d
        networks:
            - backend
        environment: 
            - MYSQL_ROOT_PASSWORD=@1234Fd#
            - bind-address=0.0.0.0
    
    mvc:
        build :
            context: .
            dockerfile: Dockerfile
        networks :
            - backend            
        ports :
            - 5000:80
        environment :
            - DBHOST=mysql
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on :
            - mysql